"""The reward bridge: any trainer scores completions with a Nenyax environment's own verifier.

Trainers (TRL, verl, prime-rl, OpenRLHF) run in their own processes. They import a tiny generated
module that rebuilds the environment from its spec and calls :meth:`Bridge.score` for every
completion, so rewards always come from the environment, never from a copy of its logic.
"""

from __future__ import annotations

import json
import threading
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from ..environment import Environment
from ..types import TaskRef


def env_spec(env: Environment, config: dict[str, Any]) -> Any:
    """How a separate process rebuilds ``env``: ``config["env"]`` or the URI it was loaded from."""
    spec = config.get("env") or env.manifest.extra.get("uri")
    if spec is None:
        raise ValueError(
            "external trainers rebuild the environment in their own process: pass "
            'config["env"] (a URI like "reasoning_gym:basic_arithmetic", a folder, or '
            '{"use": "module:factory"}), or load the environment with nenyax.load()'
        )
    return spec


def completion_text(completion: Any) -> str:
    """The reply as text, whatever shape a trainer hands over (string, message, message list)."""
    if isinstance(completion, str):
        return completion
    if isinstance(completion, dict):
        return str(completion.get("content") or "")
    if isinstance(completion, Sequence):
        replies = [m for m in completion if isinstance(m, dict) and m.get("role") == "assistant"]
        last = replies[-1] if replies else (completion[-1] if completion else "")
        return completion_text(last)
    content = getattr(completion, "content", None)
    return str(content if content is not None else completion)


class Bridge:
    """Scores ``(task_id, completion)`` pairs against a single-turn (or one-reply) environment."""

    def __init__(self, env: Environment) -> None:
        self.env = env
        self._tasks = {t.id: t for t in env.tasks()}
        self._lock = threading.Lock()

    @classmethod
    def from_spec(cls, spec: Any) -> Bridge:
        from ..config import build_env

        return cls(build_env(spec))

    def task(self, task_id: Any) -> TaskRef:
        key = str(task_id)
        if key not in self._tasks:
            raise KeyError(f"no task {key!r} in {self.env.id}")
        return self._tasks[key]

    def score(self, task_id: Any, completion: Any) -> float:
        """Open a fresh episode on the task, give it the reply, and return the judged score."""
        text = completion_text(completion)
        # Environments are not assumed thread-safe: one episode at a time.
        with self._lock, self.env.session(task=self.task(task_id)) as session:
            session.act(text)
            return float(session.judge().score)

    def score_many(self, task_ids: Sequence[Any], completions: Sequence[Any]) -> list[float]:
        return [self.score(t, c) for t, c in zip(task_ids, completions, strict=True)]


def export_tasks(env: Environment, limit: int | None = None) -> list[dict[str, Any]]:
    """The environment's tasks as training rows: a prompt, its task id, and its answer if known."""
    rows = []
    for t in env.tasks(limit=limit):
        if not t.prompt:
            continue
        answer = t.metadata.get("answer")
        rows.append(
            {
                "task_id": t.id,
                "prompt": t.prompt,
                "answer": "" if answer is None else str(answer),
                "split": t.split or "train",
            }
        )
    if not rows:
        raise ValueError(f"{env.id} has no prompts to train on (env.tasks() is empty)")
    return rows


def split_rows(rows: list[dict[str, Any]], eval_fraction: float = 0.2, seed: int = 0):
    """A deterministic train/held-out split, so trainers never see the evaluation tasks."""
    import random

    shuffled = rows[:]
    random.Random(seed).shuffle(shuffled)
    cut = max(1, int(len(shuffled) * eval_fraction)) if len(shuffled) > 1 else 0
    return shuffled[cut:] or shuffled, shuffled[:cut]


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")
    return path


BRIDGE_MODULE = '''"""Generated by Nenyax: rewards for {trainer} come from the environment's own verifier."""

import json

from nenyax.trainers.bridge import Bridge, completion_text

SPEC = json.loads({spec!r})
_BRIDGE = None


def bridge():
    global _BRIDGE
    if _BRIDGE is None:
        _BRIDGE = Bridge.from_spec(SPEC)
    return _BRIDGE


def score(task_id, completion):
    return bridge().score(task_id, completion_text(completion))
'''


def write_bridge(workdir: Path, spec: Any, trainer: str) -> Path:
    path = workdir / "nenyax_bridge.py"
    path.write_text(BRIDGE_MODULE.format(spec=json.dumps(spec), trainer=trainer))
    return path
