"""OpenRLHF: Ray-based PPO/GRPO/REINFORCE++, rewarded by a remote reward server Nenyax runs.

OpenRLHF calls ``--remote_rm_url`` with ``{"query": [...], "prompts": [...], "labels": [...]}``
and expects ``{"rewards": [...]}``. :class:`RewardServer` is that endpoint, backed by the
environment's verifier (the label carries the task id). ``prepare`` writes the dataset and a
``reward_server.py`` sidecar and builds the ``openrlhf.cli.train_ppo_ray`` command.
"""

from __future__ import annotations

import json
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

from ..environment import Environment
from .base import Job, Requirements, Trainer, python
from .bridge import Bridge, env_spec, export_tasks, split_rows, write_bridge, write_jsonl

SERVER = '''"""Generated by Nenyax: OpenRLHF's remote reward model, backed by the environment's verifier."""

import nenyax_bridge
from nenyax.trainers.openrlhf import RewardServer

if __name__ == "__main__":
    RewardServer(nenyax_bridge.bridge(), port={port}).serve_forever()
'''


def _completion(query: str, prompt: str) -> str:
    """OpenRLHF sends prompt+completion as one string; strip the prompt back off."""
    return query[len(prompt) :] if prompt and query.startswith(prompt) else query


class RewardServer:
    def __init__(self, bridge: Bridge, host: str = "127.0.0.1", port: int = 0) -> None:
        self.bridge = bridge
        outer = self

        class Handler(BaseHTTPRequestHandler):
            def log_message(self, *args: Any) -> None:
                pass

            def do_POST(self) -> None:
                body = json.loads(
                    self.rfile.read(int(self.headers.get("Content-Length", 0))) or b"{}"
                )
                queries = body.get("query") or []
                prompts = body.get("prompts") or [""] * len(queries)
                labels = body.get("labels") or [None] * len(queries)
                rewards = [
                    outer.bridge.score(label, _completion(q, p))
                    for q, p, label in zip(queries, prompts, labels, strict=True)
                ]
                out = json.dumps({"rewards": rewards, "scores": rewards}).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(out)))
                self.end_headers()
                self.wfile.write(out)

        self.httpd = ThreadingHTTPServer((host, port), Handler)

    @property
    def url(self) -> str:
        host, port = self.httpd.server_address[:2]
        return f"http://{host}:{port}/get_reward"

    def serve_forever(self) -> None:
        self.httpd.serve_forever()

    def start(self) -> RewardServer:
        threading.Thread(target=self.httpd.serve_forever, daemon=True).start()
        return self

    def stop(self) -> None:
        self.httpd.shutdown()
        self.httpd.server_close()


class OpenRLHFTrainer(Trainer):
    id = "openrlhf"
    name = "OpenRLHF"
    summary = (
        "Ray-based PPO, GRPO and REINFORCE++; Nenyax serves the reward as a remote reward model."
    )
    config_schema = {
        "type": "object",
        "properties": {
            "advantage_estimator": {
                "enum": ["group_norm", "reinforce", "rloo", "gae"],
                "default": "group_norm",
            },
            "n_samples_per_prompt": {"type": "integer", "default": 8},
            "port": {"type": "integer", "default": 5050},
            "args": {
                "type": "object",
                "description": "any other train_ppo_ray flags, flag = value",
            },
        },
    }

    def requirements(self) -> Requirements:
        return Requirements(
            gpus=2,
            min_vram_gb=40,
            packages=["openrlhf", "ray", "vllm", "deepspeed"],
            install=["openrlhf[vllm]", "nenyax"],
            supports=["text"],
        )

    def prepare(self, env: Environment, model: str, config: dict[str, Any], workdir: Path) -> Job:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        spec = env_spec(env, config)
        train, held_out = split_rows(
            export_tasks(env, config.get("max_tasks")), seed=int(config.get("seed", 0))
        )
        port = int(config.get("port", 5050))
        files = {
            "train_data": write_jsonl(workdir / "train.jsonl", train),
            "eval_data": write_jsonl(workdir / "eval.jsonl", held_out),
            "bridge": write_bridge(workdir, spec, self.id),
            "reward_server": workdir / "reward_server.py",
        }
        files["reward_server"].write_text(SERVER.format(port=port))
        out = workdir / "checkpoint"
        flags = {
            "--pretrain": model,
            "--prompt_data": str(files["train_data"]),
            "--input_key": "prompt",
            "--label_key": "task_id",
            "--apply_chat_template": None,
            "--remote_rm_url": f"http://127.0.0.1:{port}/get_reward",
            "--advantage_estimator": config.get("advantage_estimator", "group_norm"),
            "--n_samples_per_prompt": config.get("n_samples_per_prompt", 8),
            "--save_path": str(out),
            **{f"--{k}": v for k, v in (config.get("args") or {}).items()},
        }
        command = [python(config), "-m", "openrlhf.cli.train_ppo_ray"]
        for flag, v in flags.items():
            command += [flag] if v is None else [flag, str(v)]
        return Job(
            trainer=self.id,
            workdir=workdir,
            command=command,
            files=files,
            checkpoint_dir=out,
            env={"PYTHONPATH": str(workdir)},
            sidecars=[[python(config), "reward_server.py"]],
            meta={"port": port, "train_tasks": len(train), "eval_tasks": len(held_out)},
        )
