"""prime-rl (Prime Intellect): async RL on verifiers environments, fed any Nenyax environment.

The key piece is :func:`to_verifiers`: it exposes a Nenyax step environment as a legacy
``verifiers`` Environment, so prime-rl, ``vf-eval`` and anything else built on verifiers can use
it. Single-turn environments become a ``SingleTurnEnv`` whose rubric is the Nenyax verifier;
multi-turn ones become a ``MultiTurnEnv`` that steps a live Nenyax session each turn.

``prepare`` writes a ``nenyax_verifiers_env.py`` module (``load_environment()``) and a prime-rl
``rl.toml``; the command is ``rl @ rl.toml``, run from a prime-rl checkout.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..environment import Environment
from .base import Job, Requirements, Trainer
from .bridge import completion_text, env_spec, export_tasks

ENV_MODULE = '''"""Generated by Nenyax: a verifiers environment backed by a Nenyax environment."""

import json

from nenyax.config import build_env
from nenyax.trainers.prime_rl import to_verifiers

SPEC = json.loads({spec!r})


def load_environment(**kwargs):
    return to_verifiers(build_env(SPEC), **kwargs)
'''


def _multi_turn(env: Environment) -> bool:
    return env.manifest.capabilities.reward_timing == "per_step" or bool(
        env.manifest.extra.get("multi_turn")
    )


def to_verifiers(
    env: Environment, *, max_turns: int = 20, multi_turn: bool | None = None, **_: Any
):
    """Expose a Nenyax step environment as a legacy verifiers Environment."""
    import verifiers as vf
    from datasets import Dataset

    rows = [
        {"question": r["prompt"], "answer": r["answer"], "info": {"task_id": r["task_id"]}}
        for r in export_tasks(env)
    ]
    dataset = Dataset.from_list(rows)
    tasks = {t.id: t for t in env.tasks()}
    multi = _multi_turn(env) if multi_turn is None else multi_turn

    if not multi:

        def nenyax_score(completion, info, **kw) -> float:
            with env.session(task=tasks[str(info["task_id"])]) as session:
                session.act(completion_text(completion))
                return float(session.judge().score)

        return vf.SingleTurnEnv(
            dataset=dataset,
            eval_dataset=dataset,
            rubric=vf.Rubric(funcs=[nenyax_score]),
            env_id=f"nenyax-{env.manifest.name}",
        )

    class NenyaxMultiTurnEnv(vf.MultiTurnEnv):
        """Each assistant turn is one action in a live Nenyax session."""

        async def setup_state(self, state):
            info = state.get("info") or {}
            state["nenyax_session"] = env.session(task=tasks.get(str(info.get("task_id"))))
            return state

        async def env_response(self, messages, state, **kw):
            session = state["nenyax_session"]
            step = session.act(completion_text(messages))
            reply = [
                {
                    "role": "user",
                    "content": step.observation.text or json.dumps(step.observation.data),
                }
            ]
            if session.done:
                state["final_env_response"] = reply
            return reply

    def nenyax_episode_score(state, **kw) -> float:
        session = state.get("nenyax_session")
        return float(session.judge().score) if session is not None else 0.0

    return NenyaxMultiTurnEnv(
        dataset=dataset,
        eval_dataset=dataset,
        rubric=vf.Rubric(funcs=[nenyax_episode_score]),
        max_turns=max_turns,
        env_id=f"nenyax-{env.manifest.name}",
    )


def _toml(sections: dict[str, dict[str, Any]]) -> str:
    def value(v: Any) -> str:
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return str(v)
        if isinstance(v, dict):  # a TOML inline table, not JSON
            return "{ " + ", ".join(f"{k} = {value(x)}" for k, x in v.items()) + " }"
        if isinstance(v, (list, tuple)):
            return "[" + ", ".join(value(x) for x in v) + "]"
        return json.dumps(str(v))

    lines = []
    for name, table in sections.items():
        lines.append(f"[{name}]")
        lines += [f"{k} = {value(v)}" for k, v in table.items()]
        lines.append("")
    return "\n".join(lines)


class PrimeRLTrainer(Trainer):
    id = "prime-rl"
    name = "prime-rl (Prime Intellect)"
    summary = "Async RL on verifiers environments; Nenyax exposes any step environment as one."
    config_schema = {
        "type": "object",
        "properties": {
            "max_steps": {"type": "integer", "default": 200},
            "rollouts_per_example": {"type": "integer", "default": 8, "description": "group size"},
            "batch_size": {"type": "integer", "default": 64},
            "max_turns": {"type": "integer", "default": 20},
            "sections": {"type": "object", "description": "extra rl.toml tables, merged in"},
        },
    }

    def requirements(self) -> Requirements:
        return Requirements(
            gpus=2,
            min_vram_gb=24,
            packages=["prime_rl", "verifiers", "vllm"],
            install=[
                "prime-rl (git clone https://github.com/PrimeIntellect-ai/prime-rl)",
                "verifiers",
                "nenyax",
            ],
            supports=["text", "multi-turn"],
        )

    def prepare(self, env: Environment, model: str, config: dict[str, Any], workdir: Path) -> Job:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        spec = env_spec(env, config)
        module = workdir / "nenyax_verifiers_env.py"
        module.write_text(ENV_MODULE.format(spec=json.dumps(spec)))
        out = workdir / "outputs"
        sections = {
            "model": {"name": model},
            "orchestrator": {
                "batch_size": config.get("batch_size", 64),
                "rollouts_per_example": config.get("rollouts_per_example", 8),
                "max_steps": config.get("max_steps", 200),
            },
            "orchestrator.environment": {
                "id": "nenyax_verifiers_env",
                "args": {"max_turns": config.get("max_turns", 20)},
            },
            "trainer": {"max_steps": config.get("max_steps", 200)},
            "ckpt": {"dir": str(out)},
        }
        for name, table in (config.get("sections") or {}).items():
            sections[name] = {**sections.get(name, {}), **table}
        rl = workdir / "rl.toml"
        rl.write_text(_toml(sections))
        return Job(
            trainer=self.id,
            workdir=workdir,
            command=["uv", "run", "rl", "@", str(rl)],
            files={"environment": module, "config": rl},
            checkpoint_dir=out,
            env={"PYTHONPATH": str(workdir)},
            meta={"multi_turn": _multi_turn(env), "sections": sections},
        )
