"""TRL (Hugging Face) and Unsloth: GRPO with the environment's verifier as the reward, or DPO.

``prepare`` writes ``train.jsonl`` / ``eval.jsonl`` from the environment's tasks, the reward
bridge, and ``train_trl.py``, which builds a ``GRPOTrainer`` whose reward function scores every
completion through :class:`~nenyax.trainers.bridge.Bridge`. DPO uses preference pairs from
trajectories (``config["pairs"]``, a JSONL of ``prompt/chosen/rejected``, e.g. from
``nenyax.export``). Unsloth is the same script with Unsloth's fast model loader and LoRA.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..environment import Environment
from .base import Job, Requirements, Trainer, python
from .bridge import env_spec, export_tasks, split_rows, write_bridge, write_jsonl

GRPO_DEFAULTS = {
    "max_steps": 200,
    "learning_rate": 1e-6,
    "per_device_train_batch_size": 8,
    "num_generations": 8,
    "max_completion_length": 512,
    "beta": 0.0,
    "logging_steps": 1,
    "save_steps": 50,
    "bf16": True,
}

SCRIPT = '''"""Generated by Nenyax: {method} on a Nenyax environment with TRL{unsloth_note}."""

import json
import sys

from datasets import load_dataset
from transformers import TrainerCallback

import nenyax_bridge

CONFIG = json.loads({config!r})
MODEL = CONFIG["model"]
OUT = CONFIG["output_dir"]


class NenyaxMetrics(TrainerCallback):
    """Print trainer logs as NENYAX_METRIC lines, which Nenyax streams as live round events."""

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            row = {{"step": state.global_step, **{{k: v for k, v in logs.items() if isinstance(v, (int, float))}}}}
            print("NENYAX_METRIC " + json.dumps(row), flush=True)


def nenyax_reward(completions, task_id, **kwargs):
    """One reward per completion, from the environment's own verifier."""
    return [nenyax_bridge.score(t, c) for t, c in zip(task_id, completions)]


def load_model():
{load_model}


def main():
    model, tokenizer = load_model()
{body}
    trainer.add_callback(NenyaxMetrics())
    trainer.train()
    trainer.save_model(OUT)
    tokenizer.save_pretrained(OUT)
    print("NENYAX_METRIC " + json.dumps({{"done": True, "checkpoint": OUT}}), flush=True)


if __name__ == "__main__":
    sys.exit(main())
'''

LOAD_HF = """    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    model = AutoModelForCausalLM.from_pretrained(MODEL, torch_dtype="auto")
    return model, tokenizer"""

LOAD_UNSLOTH = """    from unsloth import FastLanguageModel

    model, tokenizer = FastLanguageModel.from_pretrained(
        MODEL, max_seq_length=CONFIG.get("max_seq_length", 2048), load_in_4bit=CONFIG.get("load_in_4bit", True)
    )
    model = FastLanguageModel.get_peft_model(
        model, r=CONFIG.get("lora_rank", 16), lora_alpha=CONFIG.get("lora_rank", 16),
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    )
    return model, tokenizer"""

GRPO_BODY = """    from trl import GRPOConfig, GRPOTrainer

    data = load_dataset("json", data_files={{"train": "train.jsonl", "eval": "eval.jsonl"}})
    data = data.map(lambda row: {{"prompt": [{{"role": "user", "content": row["prompt"]}}]}})
    args = GRPOConfig(output_dir=OUT, **CONFIG["args"])
    trainer = GRPOTrainer(
        model=model,
        processing_class=tokenizer,
        reward_funcs=[nenyax_reward],
        args=args,
        train_dataset=data["train"],
        eval_dataset=data["eval"],
    )"""

DPO_BODY = """    from trl import DPOConfig, DPOTrainer

    data = load_dataset("json", data_files={{"train": CONFIG["pairs"]}})
    args = DPOConfig(output_dir=OUT, **CONFIG["args"])
    trainer = DPOTrainer(model=model, processing_class=tokenizer, args=args, train_dataset=data["train"])"""


class TRLTrainer(Trainer):
    id = "trl"
    name = "TRL (Hugging Face)"
    summary = (
        "GRPO with the environment's verifier as the reward function, or DPO on trajectory pairs."
    )
    config_schema = {
        "type": "object",
        "properties": {
            "method": {"enum": ["grpo", "dpo"], "default": "grpo"},
            "max_steps": {"type": "integer", "default": 200},
            "learning_rate": {"type": "number", "default": 1e-6},
            "num_generations": {"type": "integer", "default": 8, "description": "group size"},
            "max_completion_length": {"type": "integer", "default": 512},
            "pairs": {"type": "string", "description": "DPO: JSONL of prompt/chosen/rejected"},
            "args": {"type": "object", "description": "any other GRPOConfig/DPOConfig fields"},
        },
    }
    unsloth = False

    def requirements(self) -> Requirements:
        return Requirements(
            gpus=1,
            min_vram_gb=24,
            packages=["trl", "transformers", "torch", "datasets"],
            install=["trl>=0.19", "transformers", "datasets", "nenyax"],
            image="huggingface/trl:latest",
            supports=["text"],
        )

    def prepare(self, env: Environment, model: str, config: dict[str, Any], workdir: Path) -> Job:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        method = config.get("method", "grpo")
        if method not in ("grpo", "dpo"):
            raise ValueError(f"TRL method must be grpo or dpo, not {method!r}")
        spec = env_spec(env, config)
        train, held_out = split_rows(
            export_tasks(env, config.get("max_tasks")), seed=int(config.get("seed", 0))
        )
        files = {
            "train_data": write_jsonl(workdir / "train.jsonl", train),
            "eval_data": write_jsonl(workdir / "eval.jsonl", held_out),
            "bridge": write_bridge(workdir, spec, self.id),
        }
        args = {
            **GRPO_DEFAULTS,
            **{k: config[k] for k in GRPO_DEFAULTS if k in config},
            **config.get("args", {}),
        }
        if method == "dpo":
            args = {
                k: args[k]
                for k in (
                    "max_steps",
                    "learning_rate",
                    "per_device_train_batch_size",
                    "logging_steps",
                    "save_steps",
                    "bf16",
                )
            }
            args["beta"] = config.get("beta", 0.1)
            if not config.get("pairs"):
                raise ValueError("DPO needs config['pairs']: a JSONL of prompt/chosen/rejected")
        out = workdir / "checkpoint"
        script_config = {
            "model": model,
            "output_dir": str(out),
            "args": args,
            "pairs": config.get("pairs"),
            **{
                k: config[k] for k in ("lora_rank", "load_in_4bit", "max_seq_length") if k in config
            },
        }
        script = SCRIPT.format(
            method=method.upper(),
            unsloth_note=" and Unsloth" if self.unsloth else "",
            config=json.dumps(script_config),
            load_model=LOAD_UNSLOTH if self.unsloth else LOAD_HF,
            body=GRPO_BODY if method == "grpo" else DPO_BODY,
        )
        files["script"] = workdir / "train_trl.py"
        files["script"].write_text(script)
        return Job(
            trainer=self.id,
            workdir=workdir,
            command=[python(config), "train_trl.py"],
            files=files,
            checkpoint_dir=out,
            meta={
                "method": method,
                "train_tasks": len(train),
                "eval_tasks": len(held_out),
                "args": args,
            },
        )


class UnslothTrainer(TRLTrainer):
    id = "unsloth"
    name = "Unsloth"
    summary = (
        "GRPO through TRL with Unsloth's fast 4-bit loading and LoRA: fits on one smaller GPU."
    )
    unsloth = True

    def requirements(self) -> Requirements:
        return Requirements(
            gpus=1,
            min_vram_gb=12,
            packages=["unsloth", "trl", "transformers", "torch", "datasets"],
            install=["unsloth", "trl", "datasets", "nenyax"],
            image=None,
            supports=["text"],
        )
