"""verl (ByteDance Seed): GRPO/PPO at scale, rewarded by the environment's verifier.

``prepare`` exports the environment's tasks to verl's RL parquet format (``data_source``,
``prompt`` messages, ``reward_model.ground_truth``, ``extra_info.task_id``), writes
``nenyax_reward.py`` with verl's ``compute_score(data_source, solution_str, ground_truth,
extra_info)`` signature backed by the bridge, and builds the ``verl.trainer.main_ppo`` command
with Hydra overrides (``custom_reward_function.path`` points at the reward module).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..environment import Environment
from .base import Job, Requirements, Trainer, python
from .bridge import env_spec, export_tasks, split_rows, write_bridge

REWARD = '''"""Generated by Nenyax: verl's custom reward function, backed by the environment's verifier."""

import nenyax_bridge


def compute_score(data_source, solution_str, ground_truth, extra_info=None, **kwargs):
    task_id = (extra_info or {{}}).get("task_id", ground_truth)
    return nenyax_bridge.score(task_id, solution_str)
'''

DEFAULTS = {
    "algorithm.adv_estimator": "grpo",
    "data.train_batch_size": 64,
    "data.max_prompt_length": 1024,
    "data.max_response_length": 1024,
    "actor_rollout_ref.actor.optim.lr": 1e-6,
    "actor_rollout_ref.actor.use_kl_loss": False,
    "actor_rollout_ref.rollout.name": "vllm",
    "actor_rollout_ref.rollout.n": 8,
    "actor_rollout_ref.rollout.gpu_memory_utilization": 0.6,
    "trainer.total_epochs": 1,
    "trainer.n_gpus_per_node": 1,
    "trainer.nnodes": 1,
    "trainer.save_freq": 50,
    "trainer.test_freq": 25,
    "trainer.logger": "['console']",
    "trainer.project_name": "nenyax",
}


def _rows(rows: list[dict[str, Any]], source: str) -> list[dict[str, Any]]:
    return [
        {
            "data_source": source,
            "prompt": [{"role": "user", "content": r["prompt"]}],
            "ability": "nenyax",
            "reward_model": {"style": "rule", "ground_truth": r["answer"] or r["task_id"]},
            "extra_info": {"index": i, "task_id": r["task_id"]},
        }
        for i, r in enumerate(rows)
    ]


class VerlTrainer(Trainer):
    id = "verl"
    name = "verl"
    summary = "GRPO/PPO at scale (FSDP or Megatron, vLLM rollouts) with the environment's verifier as reward."
    config_schema = {
        "type": "object",
        "properties": {
            "adv_estimator": {
                "enum": ["grpo", "gae", "rloo", "reinforce_plus_plus", "remax"],
                "default": "grpo",
            },
            "gpus": {"type": "integer", "default": 1},
            "epochs": {"type": "integer", "default": 1},
            "rollout_n": {"type": "integer", "default": 8, "description": "group size"},
            "overrides": {
                "type": "object",
                "description": "any other Hydra overrides, key = value",
            },
        },
    }

    def requirements(self) -> Requirements:
        return Requirements(
            gpus=1,
            min_vram_gb=40,
            packages=["verl", "vllm", "torch", "pandas", "pyarrow"],
            install=["verl", "vllm", "nenyax"],
            image="verlai/verl:latest",
            supports=["text"],
        )

    def prepare(self, env: Environment, model: str, config: dict[str, Any], workdir: Path) -> Job:
        import pandas as pd

        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        spec = env_spec(env, config)
        train, held_out = split_rows(
            export_tasks(env, config.get("max_tasks")), seed=int(config.get("seed", 0))
        )
        source = f"nenyax/{env.manifest.name}"
        files = {"bridge": write_bridge(workdir, spec, self.id)}
        for name, rows in (("train", train), ("eval", held_out)):
            path = workdir / f"{name}.parquet"
            pd.DataFrame(_rows(rows, source)).to_parquet(path)
            files[f"{name}_data"] = path
        files["reward"] = workdir / "nenyax_reward.py"
        files["reward"].write_text(REWARD.format())
        out = workdir / "checkpoints"
        overrides = {
            **DEFAULTS,
            "algorithm.adv_estimator": config.get(
                "adv_estimator", DEFAULTS["algorithm.adv_estimator"]
            ),
            "actor_rollout_ref.rollout.n": config.get(
                "rollout_n", DEFAULTS["actor_rollout_ref.rollout.n"]
            ),
            "trainer.n_gpus_per_node": config.get("gpus", 1),
            "trainer.total_epochs": config.get("epochs", 1),
            "data.train_files": str(files["train_data"]),
            "data.val_files": str(files["eval_data"]),
            "actor_rollout_ref.model.path": model,
            "custom_reward_function.path": str(files["reward"]),
            "custom_reward_function.name": "compute_score",
            "trainer.default_local_dir": str(out),
            "trainer.experiment_name": config.get("experiment", env.manifest.name),
            **config.get("overrides", {}),
        }
        command = [python(config), "-m", "verl.trainer.main_ppo"] + [
            f"{k}={v}" for k, v in overrides.items()
        ]
        (workdir / "verl_overrides.json").write_text(json.dumps(overrides, indent=2))
        return Job(
            trainer=self.id,
            workdir=workdir,
            command=command,
            files=files,
            checkpoint_dir=out,
            env={"PYTHONPATH": str(workdir)},
            meta={"overrides": overrides, "train_tasks": len(train), "eval_tasks": len(held_out)},
        )
